module Everything where

import Prelude
import Category

import Syntax

import CoquandRenaming
import CoquandSubstitution
import CoquandNormalisation
import CoquandConvertibility
import CoquandCompleteness

import KovacsEmbedding
import KovacsSubstitution
import KovacsNormalForm
import KovacsNormalisation
import KovacsConvertibility
import KovacsCompleteness
